const findCity = require("./findCity")
const findBySize = require("./findBySize")
const findFlightDistance = require("./findFlightDistance")

// const Chengdu = findCity("Chengdu")
// const Seattle = findCity("Seattle")
// const pamplona = findCity("pamplona", "es")
// console.log(Chengdu, Seattle, pamplona)
// console.log(findBySize(10000000))
console.log(findFlightDistance("Chengdu", "Chengdu"))